---
title: "R-Ladies for JAT Datathon (2021)"
author: "R-Ladies Philadelphia"
date: "7/05/2021"
output: pdf_document
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# About the 2021 RLadies Philly Datathon

The 2021 [RLadies Philly datathon](https://github.com/rladiesPHL/2021_datathon) aimed to connect and enable R enthusiasts in the Philadelphia region (and beyond!) to learn and collaborate while also making a difference in the broader Philadelphia community. This year, [R-Ladies Philly](https://www.rladiesphilly.org/) partnered with the [Judge Accountability Table (JAT)](https://judgeaccountabilitytable.org/) to explore judicial patterns in Philadelphia courts and better understand trends through data.  

The JAT is a coalition of organizations working toward a shared mission of holding judicial candidates and judges accountable to our community’s vision of justice. The organizations of the JAT include: Reclaim Philadelphia, Project SAFE, 215 People’s Alliance, Philadelphia Community Bail Fund, Youth Art and Self-Empowerment Project, Amistad Law Project, Coalition to Abolish Death By Incarceration (CADBI), The Center for Carceral Communities, ICE out of Courts, Pennsylvania Student Power Network, Make The Road Pennsylvania, DecarceratePA, Black Lives Matter Philadelphia. For this datathon, JAT have made available a dataset of de-identified public court docket information for defendants in Philadelphia County, PA between 2010-2020. We hope that this datathon will further their efforts to:

- Explore and describe this rich, messy data more completely (not only by answering specific questions, but also by discovering what additional information would be required to be able to answer these questions)
- Understand best approaches to stratifying and analyzing data
- Understanding predictive factors in carceral outcomes

The datathon kicked off on March 17, 2021 with a virtual meetup where participants learned about JAT's mission, the datathon goals and the available datasets, and organized themselves into groups (see kickoff [slides](https://docs.google.com/presentation/d/1iMutdI_1nyvegZ1lKVgd4EW4TguGAUMklNsFt--L8NU/edit?usp=sharing) and [recording](https://www.youtube.com/watch?v=sV4RylIrZ6w)). Teams then worked together over the course of 6 weeks, and came together again for a conclusion meetup on April 28, 2021 to share their findings with each other and the partner organization (see conclusion [slides](https://docs.google.com/presentation/d/1KhyCgos30lQfxKHooV9LUQEc7N8ma5j9LtXrJiPhjbU/edit?usp=sharing), and [recording](https://youtu.be/fzJhKMcKVX4)). 

## About this report

This report is split into three chapters, each comprised of the final report from the three participating datathon teams:

- **Team 1: Data Visualization**: Visualize judicial patterns at various levels of abstraction, and if possible, create an interactive dashboard.

- **Team 2: Defining and quantifying judge "harshness**: Conduct research and analyze data to propose metrics and a process for quantifying how harsh a judge is, considering that judges are presented with different kinds of cases (e.g., offense severity).

- **Team 3: Understanding Systemic Trends**: Examine how things have changed in the courts since [Larry Krasner](https://en.wikipedia.org/wiki/Larry_Krasner) took office in January 2018. 


