---
title: "JAT Interactive Dashboard"
author: "R-Ladies Philly Team 1"
date: "5/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Executive Summary

The docket data from Philadelphia courts is currently inaccessible to the average citizen who wants to learn more about patterns in sentencing and bail in our courts. The data is complex and difficult to work with, even for data professionals. Therefore, we sought to provide a highly interactive web interface to allow the deep interrogation of this data.

# Problem definition and dataset 

**Objective:** Visualize judicial patterns at various levels of abstraction, and if possible, create an interactive dashboard:
    - Levels of abstraction: court type, judge name, defendant demographics, crime severity
    - Patterns of interest: 
        - Process: time to disposition 
        - Bail: amount, % misdemeanor cases with return on recognizance (ROR), % of cases that received reductions in bail or changes in bail type
        - Disposition: sentence length
        - Time trends: punitive sentencing, bail decisions for particular types of offenses

### Data issues

*The current dashboard provides access to the provided data. However, it is a work-in-progess that could be augmented by additional teams*



# Results 
(3-5 pages)

# Conclusions and Next Steps 
(1 page)

# Team Contributors & Acknowledgements


<span style="color:gray">*This section should list the names and 1-2 sentence descriptions of everyone who worked on the submission. An example is listed below (please replace the example with your own info).*</span>

**Gritty McGritty, MSc** is a data scientist with Philly's DataForGood nonprofit, and a student of applied statistics at DataIsLife University. In both roles, Gritty enjoys conducting predictive analyses and natural language processing.

**Alice Walsh, PhD** is a computational biologist at Bristol Myers Squibb and an organizer of R-Ladies Philly. She enjoys data cleaning, generating hypotheses from complex data, and mentoring others.
