---
title: "EDA of docket level data"
author: "Shanti Agung"
date: "5/21/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This notebook is to explore docket level dataset.

```{r}
library(patchwork)
library(tidyverse)
```

```{r}
# Source the functions
source(file.path(rprojroot::find_root(rprojroot::is_rstudio_project),
                 "analyses", "team2", "preprocess", "sa_functions.R"))
```

```{r}
# Make sure the source file (docket details data) exists
source_file <- file.path(rprojroot::find_root(rprojroot::is_rstudio_project),
                         "data", "docket_details.csv")
stopifnot(file.exists(source_file))
```

```{r}
# load dataset
ddcols = cols(
  docket_id = col_double(),
  gender = col_character(),
  race = col_character(),
  date_of_birth = col_date(format = ""),
  arrest_date = col_date(format = ""),
  complaint_date = col_date(format = ""),
  disposition_date = col_date(format = ""),
  filing_date = col_date(format = ""),
  initiation_date = col_date(format = ""),
  status_name = col_character(),
  court_office__court__display_name = col_character(),
  current_processing_status__processing_status = col_character(),
  current_processing_status__status_change_datetime = col_date(format = ""),
  municipality__name = col_character(),
  municipality__county__name = col_character(),
  judicial_districts = col_character(),
  court_office_types = col_character(),
  court_types = col_character(),
  representation_type = col_character(),
  M = col_double(),
  M3 = col_double(),
  F1 = col_double(),
  F3 = col_double(),
  F2 = col_double(),
  M1 = col_double(),
  M2 = col_double(),
  S = col_double(),
  `F` = col_double(),
  IC = col_double(),
  H2 = col_double(),
  H1 = col_double(),
  S2 = col_double(),
  S1 = col_double(),
  S3 = col_double(),
  judge_id = col_double(),
  disposing_authority__first_name = col_character(),
  disposing_authority__middle_name = col_character(),
  disposing_authority__last_name = col_character(),
  number_prior_dockets = col_double(),
  total_confinement_days = col_double(),
  max_confinement_days = col_double(),
  age = col_double(),
  court_types_cp = col_double(),
  court_types_mc = col_double(),
  court_types_pac = col_double(),
  court_office_types_commonwealth = col_double(),
  court_office_types_criminal = col_double(),
  court_office_types_municipal = col_double(),
  court_office_types_supreme = col_double(),
  court_office_types_suprerior = col_double()
)

dockets <- readr::read_csv(source_file, col_types = ddcols)
```

```{r}
# Subset data for analysis
dockets_data <- subset_dockets(dockets)
```

```{r}
glimpse(dockets_data)
```


```{r}
# Create factors
gender_levels <- c("Female", "Male")
race_levels <- c("Asian", "Asian/Pacific Islander", "Bi-Racial", "Black",
                 "Native American/Alaskan Native", "Unknown/Unreported",
                 "White")

dockets_data <- dockets_data %>% 
  mutate(gender = factor(gender, level = gender_levels),
         race = factor(race, level = race_levels),
         court_types_cp = factor(court_types_cp),
         court_types_mc = factor(court_types_mc),
         court_types_pac = factor(court_types_pac),
         judge_id = factor(judge_id),
         year = factor(year, ordered = TRUE))
```

# Descriptive

## judges
How many judges are there?
```{r}
dockets_data %>% 
  distinct(judge_id) %>% 
  count()
```

Number of judges in each year
```{r}
dockets_data %>% 
  distinct(judge_id, year) %>% 
  ggplot(aes(x = year)) +
  geom_bar()
```

Number of cases per judge
```{r}
dockets_data %>% 
  count(judge_id) %>% 
  ggplot(aes(x = n)) +
  geom_histogram(binwidth = 200)
```
