---
title: "Descriptive title of analysis"
subtitle: "2021 RLadies Philly/JAT Datathon"
author: "Team 1/2/3/etc."
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Executive Summary (1 page)
<span style="color:gray">*This section should have up to 5 bullet points summarizing the main conclusions from the analysis. These should be worded in such a way that people who are not data experts can easily understand what actions could be considered given the analysis results. *</span>

## Contributors (1 page)

<span style="color:gray">*This section should list the names and 1-2 sentence descriptions of everyone who worked on the submission. An example is listed below (please replace the example with your own info).*</span>

**Gritty McGritty, MSc** is a data scientist with Philly's DataForGood nonprofit, and a student of applied statistics at DataIsLife University. In both roles, Gritty enjoys conducting predictive analyses and natural language processing.

## Problem definition and dataset (1-2 pages)

<span style="color:gray">*Summarize the research question/area your team has worked on.*</span>

### Working definitions

*Include here any working definitions that you used (beyond what was outlined in the general description)*

### Data issues

*Include any issues or challenges that you noticed in the data, that may be relevant, and any actions taken*

## Results (3-5 pages)

<span style="color:gray">*You may structure this section in any way that makes results easier to understand and describe.*</span>

## Conclusions and Next Steps (1 page)

<span style="color:gray">*This section should have a bulletpoint list of what conclusions can be drawn from the analyses that were performed, and what next steps should be taken by JAT or anyone working in this area*</span>